name: example
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  iconsax_flutter:
    path: ../
  url_launcher: any
  google_fonts: any
  hooks_riverpod: any
  flutter_hooks: ^0.20.3
  flutter_riverpod: any
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true


  assets:
    - assets/images/
