name: iconsax_flutter
description: A Flutter package for Iconsax Icons.
version: 1.0.0
repository: https://github.com/PersianFlutter/iconsax_flutter

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: FlutterIconsax
      fonts:
        - asset: fonts/FlutterIconsax.ttf